version: "2"

services:
  app:
    image: node:lts-alpine
    container_name: ceres-api-dev
    user: "node"
    working_dir: /home/node/app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/home/node/app
    command: "npm run dev"
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    container_name: ceres-api-db-dev
    environment:
      POSTGRES_DATABASE: ${DB_DEV_NAME}
      POSTGRES_USER: ${DB_DEV_USER}
      POSTGRES_PASSWORD: ${DB_DEV_PASSWORD}

  adminer:
    image: adminer
    ports:
      - 4002:8080
    depens_on:
      - db
