version: "3.7"

services:
  app:
    image: node:lts-alpine
    container_name: ceres-api-dev
    user: "node"
    working_dir: /home/node/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/home/node/app
    command: "npm run dev"
    depends_on:
      - db

  db:
    image: mariadb:10
    container_name: ceres-api-db-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
